# action.yml
name: "DT automation CLI dockerize version"
description: "Test the CLI using the docker version"
inputs:
  dt-url:
    description: "Dynatrace URL"
    required: true
  dt-account-urn:
    description: "Dynatrace account URN"
    required: true
  dt-client-id:
    description: "Dynatrace client id for oauth"
    required: true
  dt-client-secret:
    description: "Dynatrace secret for oauth"
    required: true
  dt-sso-url:
    description: "Dynatrace sso url for oauth"
    required: true
  dt-service-name:
    description: "Service name for the evaluation"
    required: true
  dt-stage-name:
    description: "Stage name for the evaluation"
    required: true
  srg-start-time:
    description: "Start time for the evaluation"
    required: false
  srg-end-time:
    description: "End time for the evaluation"
    required: false
  srg-timespan:
    description: "Timespan for the evaluation"
    required: false
outputs:
  eval-result:
    description: "evaluation result"
runs:
  using: "docker"
  image: "dynatraceace/dt-automation-cli:azdo"
  entrypoint: "dta"
  env:
    LOG_LEVEL: "verbose"
    DYNATRACE_URL_GEN3: ${{ inputs.dt-url }}
    ACCOUNT_URN: ${{ inputs.dt-account-urn }}
    DYNATRACE_CLIENT_ID: ${{ inputs.dt-client-id}}
    DYNATRACE_SECRET: ${{ inputs.dt-client-secret}}
    DYNATRACE_SSO_URL: ${{ inputs.dt-sso-url}}
    SRG_EVALUATION_TIMESPAN: ${{ inputs.srg-timespan}}
    SRG_EVALUATION_STOP_ON_FAILURE: "true"
    SRG_EVALUATION_SERVICE: ${{ inputs.dt-service-name }}
    SRG_EVALUATION_STAGE: ${{ inputs.dt-stage-name }}
    # SRG_EVALUATION_START_TIME: ${{ inputs.srg-start-time}} # if you enable this, remove the SRG_EVALUATION_TIMESPAN
    # SRG_EVALUATION_END_TIME: ${{ inputs.srg-end-time}}
  args:
    - srg
    - evaluate
