name: "Build-push github"
description: "Builds and push the docker images to docker"
author: Diego Quispe
inputs:
  docker-folder:
    description: "dockerfile location"
    required: true
  user:
    description: "user"
    required: true
  token:
    description: "token"
    required: true
  repo-url:
    description: "url with image name"
    required: true
  description:
    description: "short description"
    required: true
  readmepath:
    description: "Readme filepath"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.user }}
        password: ${{ inputs.token }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ inputs.repo-url }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable=${{ contains(github.ref,'dev') || contains(github.ref,'10-feature') }}
          type=raw,value=release,enable=${{ contains(github.ref,'release') }}
        labels: |
          org.opencontainers.image.title=${{ inputs.repo-url }}

    - name: Debug
      shell: bash
      working-directory: ${{ inputs.docker-folder }}
      run: |
        pwd
        cd ./executables
        ls

    - name: Build and push Docker
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.docker-folder }}
        file: ${{ inputs.docker-folder }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ inputs.user }}
        password: ${{ inputs.token }}
        repository: ${{ inputs.repo-url }}
        readme-filepath: ${{ inputs.readmepath }}
        short-description: ${{ inputs.description }}
