name: "Build CLI "
description: "Builds the CLI and outputs the binary"
author: Diego Quispe
inputs:
  build-dir:
    description: "build directory"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: npm install
      shell: bash
      run: npm install
      working-directory: ${{ inputs.build-dir }}
    - name: npm run pack
      shell: bash
      working-directory: ${{ inputs.build-dir }}
      run: |
        npm i -g @vercel/ncc
        npm run pack

    - name: Debug
      shell: bash
      working-directory: ${{ inputs.build-dir }}
      run: |
        pwd
        cd ./executables
        ls
