name: "Github Release"
description: "Creates a new release in github"
inputs:
  cli-files:
    description: "cli folder"
    required: true
  release-docs:
    description: "release docs"
    required: true
runs:
  using: "composite"
  steps:
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
        files: |
          ${{ inputs.cli-files }}
