name: pull-request
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run integration tests
        run: npm run test-integration
        env:
          ACCOUNT_URN: "${{ secrets.ACCOUNT_URN }}"
